src2obj = 100
det2obj = 50
det_pixel = 0.1
img_pixel = 0.05
unit = "mm"
axs_tan = 0
vol_rot = [ 0.0, 0.0, 0.0,]
vol_tra = [ 0.0, 0.0, 0.0,]
det_sample = [ 1, 1,]
vol_sample = [ 1, 1, 1,]
ang_range = [ 0, 180,]
src_ort = 0
src_tan = 0
det_ort = 0
det_tan = 0
det_roll = 0
det_pitch = 0
det_yaw = 0
axs_roll = 0
axs_pitch = 0
